# Generated by Django 4.0.6 on 2022-08-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokepals_app', '0002_pokemon_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
