# Generated by Django 4.0.6 on 2022-08-02 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokepals_app', '0005_alter_pokemon_cry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='last_fed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
