# Generated by Django 4.0.6 on 2022-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepals_app', '0006_alter_pokemon_last_fed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='happiness',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hunger',
            field=models.IntegerField(default=5),
        ),
    ]
